SELECT
    CUSTOMER_ID AS CUSTOMER_ID,
	CUSTOMER_UNIQUE_ID AS CUSTOMER_UNIQUE_ID,
	CUSTOMER_ZIP_CODE_PREFIX AS CUSTOMER_ZIP_CODE_PREFIX,
	CUSTOMER_CITY AS CUSTOMER_CITY,
	CUSTOMER_STATE AS CUSTOMER_STATE
FROM {{ source('ECOM_RAW_STAGING', 'CUSTOMERS') }}