SELECT
	ORDER_ID AS ORDER_ID,
	REVIEW_ID AS REVIEW_ID,
	REVIEW_SCORE AS REVIEW_SCORE,
	REVIEW_COMMENT_TITLE AS REVIEW_COMMENT_TITLE,
	REVIEW_COMMENT_MESSAGE AS REVIEW_COMMENT_MESSAGE,
	REVIEW_CREATION_DATE AS REVIEW_CREATION_DATE,
	REVIEW_ANSWER_TIMESTAMP AS REVIEW_ANSWER_TIMESTAMP,
    _business_date,
    _ingested_at,
    _source_file
FROM {{ source('ECOM_RAW_STAGING', 'REVIEWS') }}