SELECT 
    ORDER_ID AS ORDER_ID,
	CUSTOMER_ID AS CUSTOMER_ID,
	ORDER_STATUS AS ORDER_STATUS,
	ORDER_PURCHASE_TIMESTAMP AS ORDER_PURCHASE_TIMESTAMP,
	ORDER_APPROVED_AT AS ORDER_APPROVED_AT,
	ORDER_DELIVERED_CARRIER_DATE AS ORDER_DELIVERED_CARRIER_DATE,
	ORDER_DELIVERED_CUSTOMER_DATE AS ORDER_DELIVERED_CUSTOMER_DATE,
	ORDER_ESTIMATED_DELIVERY_DATE AS ORDER_ESTIMATED_DELIVERY_DATE,
    _business_date,
    _ingested_at,
    _source_file
FROM {{ source('ECOM_RAW_STAGING', 'ORDERS') }}