SELECT
	ORDER_ID AS ORDER_ID,
	ORDER_ITEM_ID AS ORDER_ITEM_ID,
	PRODUCT_ID AS PRODUCT_ID,
	SELLER_ID AS SELLER_ID,
	SHIPPING_LIMIT_DATE AS SHIPPING_LIMIT_DATE,
	PRICE AS PRICE,
	FREIGHT_VALUE AS FREIGHT_VALUE
FROM {{ source('ECOM_RAW_STAGING', 'ORDER_ITEMS') }}