SELECT 
	ORDER_ID AS ORDER_ID,
	PAYMENT_SEQUENTIAL AS PAYMENT_SEQUENTIAL,
	PAYMENT_TYPE AS PAYMENT_TYPE,
	PAYMENT_INSTALLMENTS AS PAYMENT_INSTALLMENTS,
	PAYMENT_VALUE AS PAYMENT_VALUE,
    _business_date,
    _ingested_at,
    _source_file
FROM {{ source('ECOM_RAW_STAGING', 'PAYMENTS') }}