SELECT
	PRODUCT_ID AS PRODUCT_ID,
	UPPER(TRIM(PRODUCT_CATEGORY_NAME)) AS PRODUCT_CATEGORY_NAME,
	PRODUCT_NAME_LENGTH AS PRODUCT_NAME_LENGTH,
	PRODUCT_DESCRIPTION_LENGTH AS PRODUCT_DESCRIPTION_LENGTH,
	PRODUCT_PHOTOS_QTY AS PRODUCT_PHOTOS_QTY,
	PRODUCT_WEIGHT_G AS PRODUCT_WEIGHT_G,
	PRODUCT_LENGTH_CM AS PRODUCT_LENGTH_CM,
	PRODUCT_HEIGHT_CM AS PRODUCT_HEIGHT_CM,
	PRODUCT_WIDTH_CM AS PRODUCT_WIDTH_CM,
    _business_date,
    _ingested_at,
    _source_file
FROM {{ source('ECOM_RAW_STAGING', 'PRODUCTS') }}