SELECT
    GEOLOCATION_ZIP_CODE_PREFIX AS GEOLOCATION_ZIP_CODE_PREFIX,
	GEOLOCATION_LAT AS GEOLOCATION_LAT,
	GEOLOCATION_LNG AS GEOLOCATION_LNG,
	GEOLOCATION_CITY AS GEOLOCATION_CITY,
	GEOLOCATION_STATE AS GEOLOCATION_STATE
FROM {{ source('ECOM_RAW_STAGING', 'GEOLOCATION') }}