SELECT 
	SELLER_ID AS SELLER_ID,
	SELLER_ZIP_CODE_PREFIX AS SELLER_ZIP_CODE_PREFIX,
	UPPER(TRIM(SELLER_CITY)) AS SELLER_CITY,
	UPPER(TRIM(SELLER_STATE)) AS SELLER_STATE
FROM {{ source('ECOM_RAW_STAGING', 'SELLERS') }}
